const actionsTypes = {
  GET_VALUES : 'GET_VALUES',
  GET_EXTERNAL_VALUES: 'GET_EXTERNAL_VALUES',
  TOGGLE_MENU: 'TOGGLE_MENU',
  DARK_MODE: 'DARK_MODE',
  INTERNAL_SEARCH: 'INTERNAL_SEARCH',
  EXTERNAL_SEARCH: 'EXTERNAL_SEARCH',

}

export { actionsTypes }